(()=>{
const API=()=>localStorage.getItem('aither-backend-url')||'https://aitherbackendnew.onrender.com';
const TOKEN_KEY='aither-session-token';
const escA=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const button=document.createElement('button');button.id='aitherAccountButton';button.type='button';button.setAttribute('aria-label','Account');button.title='Aither Account';button.textContent='●';document.querySelector('.toolbar')?.appendChild(button);
const modal=document.createElement('div');modal.className='account-modal hidden';modal.innerHTML='<div class="account-card"><div class="account-head"><div><div class="account-kicker">AITHER ACCOUNT</div><h2>Aither Account</h2></div><button class="account-close" type="button">×</button></div><div id="accountBody"></div></div>';document.body.appendChild(modal);
const body=modal.querySelector('#accountBody');let mode='login',current=null,auth=null,fb=null;
async function firebase(){if(fb)return fb;const [app,m]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js')]);const config=(await import('./firebase-config.js')).default;auth=m.getAuth(app.initializeApp(config));fb={...m};return fb}
async function request(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};const token=localStorage.getItem(TOKEN_KEY)||'';if(token)headers.Authorization='Bearer '+token;const r=await fetch(API()+path,{...options,credentials:'include',headers,cache:'no-store'});let data={};try{data=await r.json()}catch{}if(!r.ok)throw Error(data.detail||'Aither Backend request failed.');return data}
async function exchange(user){if(!user)return null;const idToken=await user.getIdToken();const result=await request('/api/auth/firebase',{method:'POST',body:JSON.stringify({id_token:idToken})});if(result.session_token)localStorage.setItem(TOKEN_KEY,result.session_token);current=result.user;render();return result}
function render(){if(current){body.innerHTML=`<div class="account-user"><strong>${escA(current.name)}</strong><small>${escA(current.email)}</small></div><div class="account-actions"><button class="account-secondary" id="accountLogout" type="button">Log out</button></div>`;body.querySelector('#accountLogout').onclick=logout;return}body.innerHTML=`<form class="account-form" id="accountForm">${mode==='register'?'<label>Name<input name="name" autocomplete="name" required maxlength="80"></label>':''}<label>Email<input name="email" type="email" autocomplete="email" required></label><label>Password<input name="password" type="password" autocomplete="${mode==='register'?'new-password':'current-password'}" minlength="8" required></label><button class="account-submit" type="submit">${mode==='register'?'Create account':'Sign in'}</button></form><button class="account-google" id="accountGoogle" type="button">Continue with Google</button><div class="account-status" id="accountStatus"></div><button class="account-switch" id="accountSwitch" type="button">${mode==='register'?'Already have an account? Sign in':'Need an account? Create one'}</button>`;body.querySelector('#accountForm').onsubmit=submit;body.querySelector('#accountSwitch').onclick=()=>{mode=mode==='register'?'login':'register';render()};body.querySelector('#accountGoogle').onclick=googleSignIn}
async function submit(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget)),status=body.querySelector('#accountStatus');status.textContent='Signing in with Firebase…';try{const m=await firebase();let cred;if(mode==='register'){cred=await m.createUserWithEmailAndPassword(auth,data.email,data.password);if(data.name)await m.updateProfile(cred.user,{displayName:data.name})}else cred=await m.signInWithEmailAndPassword(auth,data.email,data.password);await exchange(cred.user)}catch(err){status.textContent=err.message?.replace('Firebase: ','')||'Authentication failed.'}}
async function googleSignIn(){const status=body.querySelector('#accountStatus');status.textContent='Opening Google sign-in…';try{const m=await firebase();const cred=await m.signInWithPopup(auth,new m.GoogleAuthProvider());await exchange(cred.user)}catch(err){status.textContent=err.message?.replace('Firebase: ','')||'Google sign-in failed.'}}
async function session(){try{const r=await request('/api/auth/session');current=r.authenticated?r.user:null}catch{current=null}render()}
async function logout(){try{const m=await firebase();await m.signOut(auth)}catch{}try{await request('/api/auth/logout',{method:'POST'})}catch{}localStorage.removeItem(TOKEN_KEY);current=null;render()}
button.onclick=()=>{modal.classList.remove('hidden');session()};modal.querySelector('.account-close').onclick=()=>modal.classList.add('hidden');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.add('hidden')});
firebase().then(m=>m.onAuthStateChanged(auth,user=>{if(user)exchange(user).catch(()=>session());else session()}).catch(()=>session()));render();
})();